In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
dataset =pd.read_csv('datasets_56485_108594_Breast_cancer_data.csv')

In [14]:
dataset

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     diagnosis  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
564          0  
565          0  
566          0  
567          0  
568          1  

[569 rows x 6 columns]

In [15]:
type(dataset)

pandas.core.frame.DataFrame

In [16]:
dataset.isnull().any()

mean_radius        False
mean_texture       False
mean_perimeter     False
mean_area          False
mean_smoothness    False
diagnosis          False
dtype: bool

In [17]:
x= dataset.iloc[:,0:5].values
x

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]])

In [18]:
y= dataset.iloc[:,5:].values
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [19]:
import sklearn

In [20]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [21]:
x[:,0]=lb.fit_transform(x[:,0])
x

array([[3.700e+02, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01],
       [4.260e+02, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02],
       [4.060e+02, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01],
       ...,
       [3.400e+02, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02],
       [4.290e+02, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01],
       [3.000e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
x_train

array([[4.600e+01, 1.753e+01, 6.441e+01, 3.108e+02, 1.007e-01],
       [6.600e+01, 2.198e+01, 6.879e+01, 3.599e+02, 8.801e-02],
       [3.290e+02, 1.486e+01, 1.043e+02, 8.000e+02, 9.495e-02],
       ...,
       [2.600e+01, 1.832e+01, 5.982e+01, 2.786e+02, 1.009e-01],
       [3.500e+01, 1.822e+01, 6.073e+01, 2.881e+02, 6.950e-02],
       [1.050e+02, 2.393e+01, 7.452e+01, 4.035e+02, 9.261e-02]])

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler            #feature scaling
from sklearn.pipeline import Pipeline                       #Pipeline
pipe = Pipeline([
    ('rescale', StandardScaler()),
    ('classifier', LogisticRegression())
])

In [25]:
pipe.fit(x_train,y_train)              #feauture scaling happens

C:\Users\ADITI\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('rescale',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('classifier',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [26]:
y_pred=pipe.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1], dtype=int64)

In [27]:
y_test

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9210526315789473